-d C:\wks\ework\FPGA\TangNano\console\TangConsoleDCJ11MEM\v6\TangConsoleDCJ11MEM_project\impl\gwsynthesis\TangConsoleDCJ11MEM.vg
-p GW5AST-138B-PBGA484A-1
-pn GW5AST-LV138PG484AC1/I0
-cst C:\wks\ework\FPGA\TangNano\console\TangConsoleDCJ11MEM\v6\TangConsoleDCJ11MEM_project\src\tc138k.cst
-cfg C:\wks\ework\FPGA\TangNano\console\TangConsoleDCJ11MEM\v6\TangConsoleDCJ11MEM_project\impl\pnr\device.cfg
-sdc C:\wks\ework\FPGA\TangNano\console\TangConsoleDCJ11MEM\v6\TangConsoleDCJ11MEM_project\src\TangConsoleDCJ11MEM.sdc
-bit
-tr
-ph
-timing
-ireg_not_in_iob
-oreg_not_in_iob
-ioreg_not_in_iob
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 3
-route_option 2
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
-enable_dsrm 0
